### ISSUE TITLE
needs py3 support for modern collectd

### ISSUE THREAD

**Issue by jaymzh** [chrisboulton/collectd-python-mysql#34]
Modern versions of collectd's py plugin use python3, and thus this breaks because it's not py3 compatible.

**Comment by jaymzh** [comment]
Looks like it's just the two `print` lines at the end without parenthesis!

**Comment by jaymzh** [comment]
Or not...

```
Unhandled python exception in read callback: KeyError: 'Innodb_purge_trx_id'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mysql.py", line 538, in read_callback
    mysql_status = fetch_mysql_status(conn)
  File "/usr/local/lib/python2.7/site-packages/mysql.py", line 353, in fetch_mysql_status
    status['Innodb_unpurged_txns'] = int(status['Innodb_max_trx_id']) - int(status['Innodb_purge_trx_id'])
KeyError: 'Innodb_purge_trx_id'
```

**Comment by jaymzh** [comment]
the above can be fixed by changing line 352 from:
```
if 'Innodb_max_trx_id' in status:
```
to
```
if 'Innodb_max_trx_id' in status and 'Innodb_purge_trx_id' in status:
```

I'll try to get a PR out when I get a moment, but anyone's welcome to just steal all the above and make a PR without crediting me and close this issue. They both fall under obvious fixes.

**Comment by jaymzh** [comment]
nevermind. PR attached. :)
